apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sonarqube
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: openshift-sonarqube
      appName: sonarqube
    name: openshift-sonarqube
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-sonarqube:latest
    source:
      git:
        uri: https://github.com/InfoSec812/openshift-sonarqube.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: sonarqube:latest
          namespace: labs-ci-cd
      type: Docker
    triggers:
    - github:
        secret: ${GITHUB_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: openshift-sonarqube
      appName: sonarqube
    name: openshift-sonarqube
  spec:
    replicas: 1
    selector:
      app: openshift-sonarqube
      deploymentconfig: openshift-sonarqube
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: openshift-sonarqube
          deploymentconfig: openshift-sonarqube
      spec:
        containers:
        - env:
          - name: SONARQUBE_WEB_JVM_OPTS
            value: ${SONARQUBE_WEB_JVM_OPTS}
          - name: SONARQUBE_JDBC_USERNAME
            value: ${SONARQUBE_JDBC_USERNAME}
          - name: SONARQUBE_JDBC_PASSWORD
            value: ${SONARQUBE_JDBC_PASSWORD}
          - name: SONARQUBE_JDBC_URL
            value: ${SONARQUBE_JDBC_URL}
          - name: SONARQUBE_LDAP_BINDDN
            value: ${SONARQUBE_LDAP_BINDDN}
          - name: SONARQUBE_LDAP_BINDPASSWD
            value: ${SONARQUBE_LDAP_BINDPASSWD}
          - name: SONARQUBE_LDAP_URL
            value: ${SONARQUBE_LDAP_URL}
          - name: SONARQUBE_LDAP_REALM
            value: ${SONARQUBE_LDAP_REALM}
          - name: SONARQUBE_LDAP_CONTEXTFACTORY
            value: ${SONARQUBE_LDAP_CONTEXTFACTORY}
          - name: SONARQUBE_LDAP_STARTTLS
            value: ${SONARQUBE_LDAP_STARTTLS}
          - name: SONARQUBE_LDAP_AUTHENTICATION
            value: ${SONARQUBE_LDAP_AUTHENTICATION}
          - name: SONARQUBE_LDAP_USER_BASEDN
            value: ${SONARQUBE_LDAP_USER_BASEDN}
          - name: SONARQUBE_LDAP_USER_REQUEST
            value: ${SONARQUBE_LDAP_USER_REQUEST}
          - name: SONARQUBE_LDAP_USER_REAL_NAME_ATTR
            value: ${SONARQUBE_LDAP_USER_REAL_NAME_ATTR}
          - name: SONARQUBE_LDAP_USER_EMAIL_ATTR
            value: ${SONARQUBE_LDAP_USER_EMAIL_ATTR}
          - name: SONARQUBE_LDAP_GROUP_BASEDN
            value: ${SONARQUBE_LDAP_GROUP_BASEDN}
          - name: SONARQUBE_LDAP_GROUP_REQUEST
            value: ${SONARQUBE_LDAP_GROUP_REQUEST}
          - name: SONARQUBE_LDAP_GROUP_ID_ATTR
            value: ${SONARQUBE_LDAP_GROUP_ID_ATTR}
          - name: SONARQUBE_BUILDBREAKER_MAX_ATTEMPTS
            value: ${SONARQUBE_BUILDBREAKER_MAX_ATTEMPTS}
          - name: SONARQUBE_BUILDBREAKER_INTERVAL
            value: ${SONARQUBE_BUILDBREAKER_INTERVAL}
          - name: SONARQUBE_BUILDBREAKER_THRESHOLD
            value: ${SONARQUBE_BUILDBREAKER_THRESHOLD}
          - name: SONAR_BUILDBREAKER_DISABLE
            value: ${SONAR_BUILDBREAKER_DISABLE}
          image: 172.30.223.20:5000/labs-ci-cd/openshift-sonarqube@sha256:43f439578deefa7ed642486090313cd6b144d44d514b7962322849fa6c0efe4a
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: openshift-sonarqube
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/sonarqube/data
            name: sonar-config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: sonar-config
          persistentVolumeClaim:
            claimName: sonar-config
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - openshift-sonarqube
        from:
          kind: ImageStreamTag
          name: openshift-sonarqube:latest
          namespace: labs-ci-cd
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
parameters:
- name: SONARQUBE_WEB_JVM_OPTS
  description: Extra startup properties for SonarQube (in the form of "-Dsonar.someProperty=someValue")
  value:
- name: SONARQUBE_JDBC_USERNAME
  description: Username used for SonarQube database authentication (leave blank to use ephemeral database)
  value:
- name: SONARQUBE_JDBC_PASSWORD
  description: Password used for SonarQube database authentication (leave blank to use ephemeral database)
  value:
- name: SONARQUBE_JDBC_URL
  description: Password used for SonarQube database authentication (leave blank to use ephemeral database)
  value:
- name: SONARQUBE_LDAP_BINDDN
  description: Bind DN for LDAP authentication (leave blank for local authentication)
  value:
- name: SONARQUBE_LDAP_BINDPASSWD
  description: Bind password for LDAP authentication (leave blank for local authentication)
  value:
- name: SONARQUBE_LDAP_URL
  description: LDAP URL for authentication (leave blank for local authentication)
  value:
- name: SONARQUBE_LDAP_REALM
  description: A realm defines the namespace from which the authentication entity is selected (See: https://docs.oracle.com/javase/jndi/tutorial/ldap/security/digest.html)
  value:
- name: SONARQUBE_LDAP_CONTEXTFACTORY
  description: JNDI ContextFactory class to be used
  value: com.sun.jndi.ldap.LdapCtxFactory
- name: SONARQUBE_LDAP_STARTTLS
  description: Enable StartTLS for the LDAP connection
  value: "false"
- name: SONARQUBE_LDAP_AUTHENTICATION
  description:  LDAP authentication method (simple | CRAM-MD5 | DIGEST-MD5 | GSSAPI)
  value: simple
- name: SONARQUBE_LDAP_USER_BASEDN
  description: LDAP BaseDN under which to search for user objects
  value:
- name: SONARQUBE_LDAP_USER_REQUEST
  description: LDAP filter to select user objects
  value: (&(objectClass=inetOrgPerson)(uid={login}))
- name: SONARQUBE_LDAP_USER_REAL_NAME_ATTR
  description: LDAP attribute which holds the user's full name
  value: cn
- name: SONARQUBE_LDAP_USER_EMAIL_ATTR
  description: LDAP attribute which holds the user's e-mail address
  value: mail
- name: SONARQUBE_LDAP_GROUP_BASEDN
  description: LDAP BaseDN under which to search for group objects
  value:
- name: SONARQUBE_LDAP_GROUP_REQUEST
  description: LDAP filter to select group objects
  value: (&(objectClass=groupOfUniqueNames)(uniqueMember={dn}))
- name: SONARQUBE_LDAP_GROUP_ID_ATTR
  description: LDAP attribute which holds the group's ID
  value: cn
- name: SONARQUBE_BUILDBREAKER_MAX_ATTEMPTS
  description: Build Break plugin - Max number of poll attempts
  value: "30"
- name: SONARQUBE_BUILDBREAKER_INTERVAL
  description: Build Breaker plugin - Interval to wait between poll requests
  value: "20000"
- name: SONARQUBE_BUILDBREAKER_THRESHOLD
  description: Build Breaker plugin - Threshold at which a build will instantly break
  value: "CRITICAL"
- name: SONAR_BUILDBREAKER_DISABLE
  description: Build Breaker plugin - Disable the build breaker plugin for all builds
  value: "true"
- name: GITHUB_SECRET
  description: Generated secret key for GitHub webhooks
  from: [A-Za-z0-9_+=]{36}
  generate: expression
- name: GENERIC_SECRET
  description: Generated secret key for generic webhooks
  from: [A-Za-z0-9_+=]{36}
  generate: expression